### ISSUE TITLE
Three state `CheckBox`

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/Microsoft.Maui.Graphics#181]
Could you please add third (`Indeterminate`) state to a checkbox? 
API-wise this can be done by changing type of `IsChecked` from `bool` to `bool?`, similar to how it's done in [Syncfusion's checkbox](https://help.syncfusion.com/xamarin/checkbox/getting-started#change-the-check-box-state).

I'm forced to use their checkbox just because of this feature.

**Comment by charlesroddie** [comment]
Wrong repo should be https://github.com/dotnet/maui

**Comment by maxkoshevoi** [comment]
Moved to maui: https://github.com/dotnet/maui/issues/2819
