### ISSUE TITLE
Is there going to be a release for .Net SDK 6.0.100?

### ISSUE THREAD

**Issue by jeroenlandheer** [dotnet/Microsoft.Maui.Graphics#230]
I see there's a list of 6.0.1011 releases and a bunch of releases for 6.0.100 with "-xyz" prerelease tags, but no release for 6.0.100. Is this one still coming?  (We're migrating a project here from .Net 5 to 6 and we need to move away from System.Drawing since it is no longer supported on Linux)

**Comment by swharden** [comment]
Hi @jeroenlandheer,

The project maintainers can weigh-in in case I'm mistaken, but my understanding is that the [Microsoft.Maui.Graphics NuGet package](https://www.nuget.org/packages/Microsoft.Maui.Graphics) will be kept in preview until MAUI is released (general availability / no longer preview). Note that the MAUI release will trail the .NET 6 release. According to the [Sep 14 Update on MAUI](https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/) the GA release of MAUI is targeted for Q2 of 2022.

PS: I too need to move away from System.Drawing 😅

**Comment by jeroenlandheer** [comment]
@swharden Alright, thanks 😄
