### ISSUE TITLE
[Enhancement] Add support for Bezier curves in ICanvas

### ISSUE THREAD

**Issue by kucint** [dotnet/Microsoft.Maui.Graphics#249]
ICanvas is missing a method DrawBezierLine(), which is usually available in most of graphics libraries.

**Comment by limefrogyank** [comment]
I believe this can be accomplished with `DrawPath(PathF path)`.  Then you can build the path using Bezier curves using `CurveTo(PointF controlPoint1, PointF controlPoint2, PointF point)`.

**Comment by kucint** [comment]
right. Thanks for info.
