### ISSUE TITLE
My Maui test program silently crashes when resizing the App.

### ISSUE THREAD

**Issue by CBrauer** [dotnet/Microsoft.Maui.Graphics#339]
Hey guys,
I'm trying to test Maui Graphis, in particular, "DrawLine" and "DrawString".
I have the source code at: https://github.com/CBrauer/MauiWinForms
The running program initial screen looks like:

![screen](https://user-images.githubusercontent.com/1317234/156937542-09b944bd-fa8b-4016-9cf9-8e9ecab46756.PNG)

When I  resize the running App, it silently  crashes with no error message.
Any help will be greatly appreciated.
Charles

**Comment by swharden** [comment]
> When I resize the running App, it silently crashes with no error message.

Hi @CBrauer, 

Are you sure it's "silently crashing"? It may be possible that you need to configure the Form to redraw the canvas when the size changes.

![339-2](https://user-images.githubusercontent.com/4165489/156956606-242e3108-9bc8-41fc-8eab-a099d8665919.gif)

https://github.com/swharden/Maui.Graphics/blob/main/projects/QuickstartWinForms/Form1.cs

> I have the source code at: https://github.com/CBrauer/MauiWinForms

Actually that looks like an empty repository 😅

**Comment by CBrauer** [comment]
Scott wrote: "Actually that looks like an empty repository "
How embarrassing!  I must not have committed the upload.  It' there now. Sorry.

**Comment by CBrauer** [comment]
I couldn't resist working on my test program some more.
You will find my new version at: https://github.com/CBrauer/Adventure-in-Maui-Graphics
Charles
