### ISSUE TITLE
Documentation - load image resource doesn't compile on Windows

### ISSUE THREAD

**Issue by janseris** [dotnet/Microsoft.Maui.Graphics#402]
### Description

https://docs.microsoft.com/en-us/dotnet/maui/user-interface/graphics/paint#create-an-imagepaint-object
This section shows how to draw an image on a canvas.
Loading the image doesn't work _**(does not compile)**_ on Windows (it only works on Android (I have tried Windows and Android)) and there is not any mention of this in the article and there is not any mention of how to load the image on Windows.
Isn't MAUI supposed to be cross-platform?
Isn't there any nice and clean code to load the image cross-platform?

I can see there that build action "EmbeddedResource" must be used instead of "MauiImage" which is default.
I assume that EmbeddedResource creates something like a byte[] resource while MauiImage creates a whole set of images which have specific resolution for each platform etc.

Do I have to put a duplicate image into the resources just so that the same image can be used as a image in ImageButton and at the same time drawn on a canvas (the first one requires MauiImage and the second one EmbeddedResource)?

Thank you

Edit:
- added more info:

`error CS0234: The type or namespace name 'Platform' does not exist in the namespace 'Microsoft.Maui.Graphics' (are you missing an assembly reference?)
`

![image](https://user-images.githubusercontent.com/64279914/164211514-caa24102-189b-4dc9-83d6-43bb72b8941e.png)

![image](https://user-images.githubusercontent.com/64279914/164211629-ff077f40-51e1-4660-88c5-cbca21e374e1.png)

### Steps to Reproduce

Try the example on Windows

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by VincentBu** [comment]
[janseris](https://github.com/janseris) is right. We fail to build those code on windows.

**Comment by janseris** [comment]
@VincentBu I am once again asking if there is any progress. Thank you

**Comment by VincentBu** [comment]
Sorry, I forgot to reply to your last comment... It still occurs on my side(vs main build).
`ImageSource.FromResource` and `ImageSource.FromStream` both fail to load image.

**Comment by mdbill** [comment]
I have this exact situation.  I didn't get it working yet, but I think the solution is to use a XAML markup extension explained here:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=windows
Scroll down to 'Embedded Resource' and Xaml after that.

**Comment by janseris** [comment]
> Sorry, I forgot to reply to your last comment... It still occurs on my side(vs main build). `ImageSource.FromResource` and `ImageSource.FromStream` both fail to load image.

Thanks. Is someone solving this issue? Can I help so someone will be solving the issue?
