### ISSUE TITLE
[Feature request] Set different stroke Caps at each end

### ISSUE THREAD

**Issue by Cfun1** [dotnet/Microsoft.Maui.Graphics#45]
I cannot find a straight forward approach (framework built-in, not workarounds) even in SkiaSharp, to draw an arc or a line with different stroke Caps at each end, something like attached picture (don't mind the red marks picture taken from internet).

It would be nice to be able to specify the stroke cap at each end.

![](https://i.stack.imgur.com/xQ89u.png)

**Comment by jonlipsky** [comment]
@Cfun1 That is not a feature that the underlying graphics libraries support out of the box.  When I've needed to do something similar, I create a path object that represents exactly what I want to draw and fill it.
