### ISSUE TITLE
Help me! The type or namespace name 'Platform' does not exist in the namespace 'Microsoft.Maui.Graphics'

### ISSUE THREAD

**Issue by leNam199320xx** [dotnet/Microsoft.Maui.Graphics#457]
The type or namespace name 'Platform' does not exist in the namespace 'Microsoft.Maui.Graphics'

pls i cannot find Platform Class when build MAUI windows app 

code :

public void Draw(ICanvas canvas, RectF dirtyRect)
    {
        // Drawing code goes here

        IImage image;
        Assembly assembly = GetType().GetTypeInfo().Assembly;
        using (Stream stream = assembly.GetManifestResourceStream("MemeCreator.Resources.Images.dotnet_bot.svg"))
        {
            image = PlatformImage.FromStream(stream); // error here

        }

        if (image != null)
        {
            IImage newImage = image.Resize(100, 60, ResizeMode.Stretch, true);
            canvas.DrawImage(newImage, 10, 10, newImage.Width, newImage.Height);
        }
    }

![Screenshot 2022-06-22 213120](https://user-images.githubusercontent.com/5983641/175055251-1f59bd17-d809-47f3-a3e9-08cd9f5180c0.png)

**Comment by lindexi** [comment]
@leNam199320xx See

https://github.com/dotnet/Microsoft.Maui.Graphics/blob/26443e13721a8983ea8ad2cf0c663192b05b6a2c/src/Microsoft.Maui.Graphics/PlatformImage.cs#L1-L15

**Comment by janseris** [comment]
Platform is Android version. I reported the issue with the documentation like 2 months ago but last 6 months all updates on MAUI Graphics have been just package version updates.
