### ISSUE TITLE
Color component type from `double` to `float`

### ISSUE THREAD

**Issue by mattleibow** [dotnet/Microsoft.Maui.Graphics#55]
One issue I see with the underlying component moving from `double` to `float` is more the default implicit things that will require updates:

```csharp
new Color(0.5, 0.5, 0.5, 0.5) // <- error
```

This will now fail to compile saying that there is no overload that will match and all the usages will need to have the "f" suffix added:

```csharp
new Color(0.5f, 0.5f, 0.5f, 0.5f)
```

This is not a "big" change per se, but will be annoying. However, maybe not so bad as I am sure most people use the parsing from string instead...

However this also means that any implicit usage of the components will now break and require a cast.

```csharp
var red = color.Red;
red = 0.5; // <- error
```

Relates to parent issue: #58

**Comment by charlesroddie** [comment]
Context: It currently is `float` in this library: the wording in this issues comes from the fact that Xamarin.Forms is `double`.

`double` (64bpc) is insane and only explainable by a dev typing `double` without thinking about it. `float` (32bpc) is still excessive. 

`single` (16bpc) is the appropriate floating point type, or `byte` (8bpc).

@dotMorten

**Comment by ToolmakerSteve** [comment]
@mattleibow 

> new Color(0.5, 0.5, 0.5, 0.5) breaks.

I don't think it has to:

     public Color(double a, double r, double g, double b) : this((float)a, (float)r, (float)g, (float)b) { }

We "know" Color has no use for double precision. So, throw away the precision.

**Comment by Redth** [comment]
Done.
