### ISSUE TITLE
Need converters from Maui Color/Rect/Size/Point to the native platform types

### ISSUE THREAD

**Issue by mattleibow** [dotnet/Microsoft.Maui.Graphics#64]

**Comment by Redth** [comment]
Are there any left we need/want here? Can we close this?

**Comment by Redth** [comment]
Also adding a type converter for color:
https://github.com/dotnet/Microsoft.Maui.Graphics/pull/76

**Comment by Redth** [comment]
Moved over Size/Rectangle/Point (and float counterparts) in https://github.com/dotnet/Microsoft.Maui.Graphics/pull/126
